"""gemini_hackathon.journey.level_1_syllabus_extraction — Level 1 body.

Level 1 of the British Isles Journey: extract the official syllabus
specification into structured BAML output, embed each learning
outcome via Vertex AI, and upsert the resulting chunks into the
Firestore Vector Search index.

The 4-node ADK 2 Workflow (per `adk2-tutorial/L1_graph_basics/workflow.py`
+ `gemini_hackathon/agents/workflows/pillar1_grading.py`):

    START -> fetch_syllabus_pdf -> extract_baml -> embed_chunks -> upsert_vector

Mirrors how Phase 4's `cocoindex_flows._factory.four_stage` factory
handles per-subject LC syllabuses — same BAML function, same Vertex
embedder, same VectorTarget, just driven explicitly through the
journey orchestrator instead of as a static CocoIndex App.

There are 2 `#REPLACE-*` markers a workshop participant fills in (the
REPLACE markers are the only learner-level edits; the surrounding code
is the reference implementation). See the codelab doc:
docs/journey/02_level_1_syllabus_extraction.md
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# BAML schema bridge — typed access to the generated client.
# ---------------------------------------------------------------------------


def _baml_extract(subject: str, pdf_text: str, language: str = "en") -> dict[str, Any]:
    """Call `b.ExtractCurriculumSyllabus` and normalise to a dict.

    Returns a dict (rather than the Pydantic model) so this level works
    without the BAML client compiled — `baml-py` is optional in the offline
    path. When `baml_client` isn't importable, returns the canonical
    stub-shape so the workshop still demos the embedding + upsert paths.
    """
    try:
        from baml_client import b  # type: ignore[import-not-found]

        # BAML client generated by `mise run baml:generate` expects an enum;
        # the BAML file's `LCSubjectSlug` enum maps subject slugs to enum
        # members. If the participant picks a subject not in the enum (e.g.
        # a future expansion-pack subject), this falls through to a string
        # cast — the BAML client's own validation will report the error.
        try:
            result = b.ExtractCurriculumSyllabus(
                pdf_text=pdf_text,
                subject=subject,
                language=language,
            )
        except Exception as exc:
            logger.warning("BAML extract failed (%s); falling back to stub", exc)
            return _stub_syllabus(subject, pdf_text, language)

        # Convert Pydantic -> dict for downstream embedding/upsert.
        if hasattr(result, "model_dump"):
            return result.model_dump()
        return dict(result)
    except ImportError:
        return _stub_syllabus(subject, pdf_text, language)


def _stub_syllabus(subject: str, pdf_text: str, language: str) -> dict[str, Any]:
    """The offline stub — derives 3 synthetic learning outcomes from the
    first ~3 sentences of `pdf_text` so the embed + upsert paths still
    exercise end-to-end without a Vertex BAML call.
    """
    chunks = [s.strip() for s in pdf_text.split(".") if len(s.strip()) > 30][:3]
    return {
        "subject": subject,
        "language": language,
        "stage": "LC_OL",
        "source_pdf": "",
        "module_topics": [
            {
                "title": "Stub topic (BAML offline)",
                "estimated_hours": 1,
                "type": "CORE",
                "learning_outcomes": [],
            }
        ],
        "total_learning_outcomes": len(chunks),
        "cross_curricular": [],
        "assessment_objectives": [],
        "_stub_chunks": chunks,  # consumed by the embed step below
    }


# ---------------------------------------------------------------------------
# The 4 ADK 2 workflow nodes (function nodes + one agent node).
# ---------------------------------------------------------------------------


async def fetch_syllabus_pdf(node_input: Any) -> dict[str, Any]:
    """Function node: read the local syllabus PDF for `{subnation}/{subject}/{lang}`.

    Falls back to a tiny built-in sample text in offline mode so the
    workshop still demos the full pipeline (BAML -> embed -> upsert).
    """
    subnation = (node_input or {}).get("subnation", "ireland")
    subject = (node_input or {}).get("subject", "mathematics")
    language = (node_input or {}).get("language", "en")

    sample_paths = [
        Path("data/ireland/lc_subject") / subject / language / f"{subject}_syllabus.pdf",
        Path(f"data/{subnation}/lc_subject/{subject}/syllabus.pdf"),
        Path(f"data/{subnation}/{subject}/syllabus.pdf"),
    ]
    for candidate in sample_paths:
        if candidate.exists():
            try:
                text = candidate.read_text(encoding="utf-8", errors="ignore")
                if text.strip():
                    return {"pdf_path": str(candidate), "pdf_text": text[:8000]}
            except Exception:
                continue

    # Fallback: tiny built-in syllabus sample, just enough to drive the
    # BAML -> embed -> upsert pipeline end-to-end. ~3 paragraphs of real
    # Irish Leaving Certificate maths prose so the embeddings are sensible.
    sample = (
        "Leaving Certificate Mathematics — Ordinary Level. "
        "Strand 1: Statistics and Probability — students learn to describe "
        "data distributions using mean, median, and mode, and to compute "
        "simple probabilities for independent events. "
        "Strand 2: Geometry and Trigonometry — students learn the geometry of "
        "the circle, the sine rule, and the cosine rule, and apply them to "
        "real-world problems. "
        "Strand 3: Number — students learn to manipulate real numbers, "
        "complex numbers, and arithmetic and geometric sequences."
    )
    return {"pdf_path": "<offline-stub>", "pdf_text": sample}


async def extract_baml(node_input: Any) -> dict[str, Any]:
    """Agent-adjacent function node: invoke BAML `ExtractCurriculumSyllabus`.

    In a strict ADK 2 Workflow, this would be an `Agent` node that calls
    the BAML client. Since the BAML call is deterministic + side-effecting
    (no LLM call), we model it as a function node here for parity with
    `gemini_hackathon/agents/workflows/pillar1_grading.py`'s pattern.
    """
    pdf_text = node_input.get("pdf_text", "")
    node_input.get("subnation", "ireland")
    subject = node_input.get("subject", "mathematics")
    language = node_input.get("language", "en")

    syllabus = _baml_extract(subject=subject, pdf_text=pdf_text, language=language)
    syllabus["source_pdf"] = node_input.get("pdf_path", "")
    return syllabus


async def embed_chunks(node_input: Any) -> dict[str, Any]:
    """Function node: Vertex AI embeddings of the syllabus's LOs.

    REPLACE-1: the participant wires the `VertexEmbedder` here. The
    stub below returns deterministic placeholder vectors (SHA-256 of
    each chunk) so the upsert step has something to write in offline mode.
    Replace with: `from cocoindex_flows._shared._vertex_embedder import
    VertexEmbedder; e = VertexEmbedder(); vector = await e.embed(chunk_text)`.
    """
    import hashlib

    chunks = (
        [
            t["title"]
            + ": "
            + " ".join(lo.get("text", "") for lo in t.get("learning_outcomes", []))
            for t in node_input.get("module_topics", [])
        ]
        if node_input.get("module_topics")
        else node_input.get("_stub_chunks", [])
    )

    out_chunks = []
    for idx, text in enumerate(chunks):
        if not text.strip():
            continue
        # Stub embedding: a deterministic 1536-d placeholder (the dimension
        # Vertex AI `gemini-embedding-001` returns when VECTOR_BACKEND is
        # configured for Firestore `FindNearest`). A real Vertex embed
        # call replaces this one line.
        seed = hashlib.sha256(text.encode("utf-8")).digest()
        stub = [b / 255.0 for b in (seed * 48)[:1536]]
        out_chunks.append(
            {
                "chunk_id": f"{node_input.get('subject', 'unknown')}-{idx:03d}",
                "text": text[:1000],
                "vector": stub,
            }
        )
    return {"embedded_chunks": out_chunks}


async def upsert_vector(node_input: Any) -> dict[str, Any]:
    """Function node: Firestore `FindNearest` vector upsert.

    REPLACE-2: the participant wires the `VectorTarget` here. The stub
    records the upserted chunks in an in-memory list so the workshop
    still demos end-to-end. Replace with: `from cocoindex_flows._shared.
    _vector_target import get_vector_target; v = get_vector_target();
    await v.upsert_batch([VectorRow(...)])`.
    """
    chunks = node_input.get("embedded_chunks", [])
    if not hasattr(upsert_vector, "_written"):
        upsert_vector._written = []  # type: ignore[attr-defined]
    upsert_vector._written.extend(chunks)  # type: ignore[attr-defined]
    return {"upserted_count": len(chunks), "vector_backend": "firestore (stub)"}


@dataclass
class Level1Result:
    """The Level 1 final output (the orchestrator passes this to Level 2)."""

    pdf_path: str
    syllabus: dict[str, Any]
    chunks: list[dict[str, Any]] = field(default_factory=list)
    upserted_count: int = 0
    vector_backend: str = ""


async def run_level_1(
    *, subnation: str = "ireland", subject: str = "mathematics", language: str = "en"
) -> Level1Result:
    """The Level 1 entrypoint — runs the 4-node pipeline and returns the structured result.

    Called by the journey orchestrator (Stream C.3) and by the standalone
    `python -m gemini_hackathon.journey.level_1_syllabus_extraction.app`
    Gradio app.
    """
    fetch = await fetch_syllabus_pdf(
        {"subnation": subnation, "subject": subject, "language": language}
    )
    baml = await extract_baml(
        {**fetch, "subnation": subnation, "subject": subject, "language": language}
    )
    embedded = await embed_chunks(baml)
    upserted = await upsert_vector(embedded)
    return Level1Result(
        pdf_path=fetch.get("pdf_path", ""),
        syllabus=baml,
        chunks=embedded.get("embedded_chunks", []),
        upserted_count=upserted.get("upserted_count", 0),
        vector_backend=upserted.get("vector_backend", ""),
    )


__all__ = [
    "Level1Result",
    "embed_chunks",
    "extract_baml",
    "fetch_syllabus_pdf",
    "run_level_1",
    "upsert_vector",
]
