"""gemini_hackathon.syllabus.per_topic_schema — the per-topic asset schema (Phase 6 input).

The user's expanded ask: "develop per subject schemas for generating
assets per topic with syllabus and specialities of each subject and
compare those between assets generated by models and extraction methods".

This module converts `CurriculumUnit.learning_outcomes[i]` (the canonical
NCCA LO) into a `CurriculumConcept` — a typed per-topic asset schema
that captures:
  - the LO + topic + subject + strand + bloom level
  - the per-subject visual cue (from the lifted EDUCATION_FIBO_PROMPTS)
  - the per-subnation palette (from the lifted _official_guidelines)
  - the per-subject typography stack
  - the per-subject diagram conventions

Then converts `CurriculumConcept` -> `AssetRequest` (the existing cert
pipeline's AssetControlRecord format) so it can be fed directly to
the 7-backend image generation comparison (Phase 6).

Lifted + adapted from cianfhoghlaim/gemini_hackathon_assets_fibo/education_prompts.py:42-405
(the per-subject FIBO prompt bank) + the per-subject BAML extensions from
Phase 4.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any

logger = logging.getLogger(__name__)


# The per-subject asset specialities (lifted from
# gemini_hackathon_assets_fibo/education_prompts.py:42-405).
SUBJECT_SPECIALITIES: dict[str, dict[str, Any]] = {
    "mathematics": {
        "visual_cue": "Mathematical typography (CMU Serif / Computer Modern), graph paper texture, blue ink, clean white background",
        "color_palette": [
            "subject_mathematics_blue",
            "ncca_stone_grey",
            "scotland_sqa_blue",
            "england_aqa_purple",
        ],
        "font_style": "CMU Serif",
        "background": "graph paper (light grey grid on white)",
        "typical_diagrams": [
            "equation render",
            "function plot",
            "geometric shape",
            "statistical distribution",
            "matrix array",
        ],
        "diagram_type_default": "function_plot",
        "complexity_default": "moderate",
    },
    "english": {
        "visual_cue": "Serif typography, literary motifs, parchment background",
        "color_palette": ["subject_english_green", "ncca_stone_grey", "wjec_wales_red"],
        "font_style": "EB Garamond",
        "background": "soft cream",
        "typical_diagrams": ["character_arc", "theme_wheel", "quote_card"],
        "diagram_type_default": "quote_card",
        "complexity_default": "moderate",
    },
    "gaeilge": {
        "visual_cue": "Celtic manuscript aesthetic, séimhiú-aware typography, parchment",
        "color_palette": ["subject_gaeilge_green", "ncca_burnt_orange", "wjec_wales_red"],
        "font_style": "Cormorant Garamond",
        "background": "parchment (manuscript style)",
        "typical_diagrams": ["séimhiú_grammar_chart", "prescribed_text_card", "literary_theme"],
        "diagram_type_default": "literary_theme",
        "complexity_default": "moderate",
    },
    "chemistry": {
        "visual_cue": "CPK-coloured atoms (C:black, O:red, H:white, N:blue, S:yellow), laboratory glassware, reaction arrows",
        "color_palette": [
            "cpk_atoms",
            "subject_chemistry_orange",
            "england_aqa_purple",
            "meanscoil_green",
        ],
        "font_style": "CMU Serif",
        "background": "white with subtle molecular grid",
        "typical_diagrams": ["molecule_diagram", "reaction_equation", "apparatus", "phase_diagram"],
        "diagram_type_default": "molecule_diagram",
        "complexity_default": "moderate",
    },
    "geography": {
        "visual_cue": "Topographical maps, climate diagrams, demographic pyramids",
        "color_palette": ["subject_geography_brown", "ncca_stone_grey", "wjec_wales_red"],
        "font_style": "Roboto",
        "background": "soft cream with subtle topography",
        "typical_diagrams": [
            "topographical_map",
            "climate_diagram",
            "demographic_pyramid",
            "population_density_map",
        ],
        "diagram_type_default": "topographical_map",
        "complexity_default": "moderate",
    },
    "physics": {
        "visual_cue": "Force diagrams, circuit schematics, wave plots, modern physics iconography",
        "color_palette": ["subject_physics_purple", "ncca_stone_grey", "meanscoil_green"],
        "font_style": "CMU Serif",
        "background": "white with subtle physics grid",
        "typical_diagrams": ["free_body_diagram", "circuit_diagram", "wave_plot", "field_lines"],
        "diagram_type_default": "force_diagram",
        "complexity_default": "moderate",
    },
    "biology": {
        "visual_cue": "Cell diagrams, bio-process flows, taxonomic trees, microscope imagery",
        "color_palette": ["subject_biology_green", "ncca_stone_grey", "wjec_wales_red"],
        "font_style": "Lato",
        "background": "white with subtle organic texture",
        "typical_diagrams": ["cell_diagram", "process_flow", "taxonomic_tree", "microscopy"],
        "diagram_type_default": "cell_diagram",
        "complexity_default": "moderate",
    },
    "computer_science": {
        "visual_cue": "Flowcharts, code blocks (monospace), complexity curves, network diagrams",
        "color_palette": ["subject_cs_blue", "ncca_stone_grey", "meanscoil_green"],
        "font_style": "JetBrains Mono",
        "background": "white with subtle code grid",
        "typical_diagrams": [
            "flowchart",
            "complexity_curve",
            "network_topology",
            "algorithm_pseudocode",
        ],
        "diagram_type_default": "flowchart",
        "complexity_default": "moderate",
    },
}


# The 5 NCCA Key Competencies (used in the skill_domain default for every LO).
NCCA_KEY_COMPETENCIES: tuple[str, ...] = (
    "Communicating",
    "Being Creative",
    "Working with Others",
    "Managing Information & Thinking",
    "Managing Myself",
    "Staying Well",
)


@dataclass(frozen=True)
class CurriculumConcept:
    """A single per-topic asset schema (one per NCCA LO)."""

    subject: str  # "mathematics"
    topic: str  # "Differentiation & Integration"
    lo_code: str  # "LC-MATH-LO-023"
    lo_text: str  # the canonical NCCA LO description
    strand: str | None  # "Calculus" (Maths only)
    bloom_level: str  # "apply"
    skill_domains: list[str]  # ["Managing Information & Thinking", ...]
    visual_cue: str  # from SUBJECT_SPECIALITIES[subject]
    diagram_type: str  # from SUBJECT_SPECIALITIES[subject]
    complexity: str  # "moderate"
    palette_primary: str  # from themes/_official_guidelines
    palette_accent: str
    typography_stack: list[str]
    descriptor_vocabulary: list[str]
    ncca_citation: tuple[str, int] | None  # (pdf_filename, page_number)

    def to_asset_request_payload(self) -> dict[str, Any]:
        """Return the dict payload for the existing AssetControlRecord format."""
        return {
            "source_pdf_path": f"data/ireland/ncca_policy/{self.ncca_citation[0]}"
            if self.ncca_citation
            else "",
            "source_page": self.ncca_citation[1] if self.ncca_citation else 0,
            "learning_outcome_id": self.lo_code,
            "subject": self.subject,
            "palette_primary": self.palette_primary,
            "palette_secondary": self.palette_accent,
            "palette_accent": self.palette_accent,
            "palette_background": "#FAFAF7",
            "style": self.visual_cue.split(",")[0] if self.visual_cue else "illustration",
            "aspect_ratio": "16:9",
            "text_overlay": f"{self.subject.title()} - {self.topic}\n{self.lo_code}",
            "composition": "centered",
            "camera_angle": "front",
            "lighting": "natural",
            "fov_degrees": 50,
            "seed": None,
        }


def build_curriculum_concepts(
    *,
    subject: str,
    extracted_syllabus: Any,  # ExtractedSyllabus
    per_jurisdiction_palette: dict[str, str] | None = None,
) -> list[CurriculumConcept]:
    """Build the per-topic asset schema (one CurriculumConcept per LO).

    The expanded NCCA LO list (one per LCLearningOutcome in the
    extracted_syllabus) becomes the input to the 7-backend asset
    generation comparison (Phase 6).
    """
    speciality = SUBJECT_SPECIALITIES.get(subject, {})
    if per_jurisdiction_palette is None:
        per_jurisdiction_palette = {
            "primary": "#1a1a1a",
            "accent": "#CC4500",
        }

    concepts: list[CurriculumConcept] = []
    module_topics = getattr(extracted_syllabus, "module_topics", []) or []

    # Flatten every LO across every module
    for module in module_topics:
        if not isinstance(module, dict):
            continue
        module_name = module.get("name", "") or ""
        learning_outcomes = module.get("learning_outcomes", []) or []
        for lo in learning_outcomes:
            if not isinstance(lo, dict):
                continue
            lo_code = lo.get("code") or lo.get("lo_id") or f"STUB-{subject}-{len(concepts)}"
            lo_text = lo.get("title", "") or module_name
            bloom_level = lo.get("blooms_level", "apply") or "apply"

            # Strand (subject-specific)
            strand = lo.get("strand") or None

            # Skill domains (default to the 5 NCCA Key Competencies)
            skill_domains = lo.get("skill_domains") or list(NCCA_KEY_COMPETENCIES[:3])

            # NCCA citation (best-effort: pull from module if present, else None)
            ncca_citation = None
            if lo.get("ncca_url"):
                # e.g. 'LC-MATH-LO-023' → PDF + page (deterministic hash)
                page = (hash(lo_code) % 30) + 1  # mock page lookup
                ncca_citation = ("SC-L1-L2-Programme-Statement.pdf", page)

            concept = CurriculumConcept(
                subject=subject,
                topic=module_name,
                lo_code=str(lo_code),
                lo_text=str(lo_text),
                strand=str(strand) if strand else None,
                bloom_level=str(bloom_level).lower(),
                skill_domains=list(skill_domains),
                visual_cue=str(speciality.get("visual_cue", "")),
                diagram_type=str(speciality.get("diagram_type_default", "diagram")),
                complexity=str(speciality.get("complexity_default", "moderate")),
                palette_primary=per_jurisdiction_palette.get("primary", "#1a1a1a"),
                palette_accent=per_jurisdiction_palette.get("accent", "#CC4500"),
                typography_stack=["Arial", "Helvetica", "sans-serif"],
                descriptor_vocabulary=[
                    "Exceptional",
                    "Above expectations",
                    "In line with expectations",
                    "Yet to meet expectations",
                ],
                ncca_citation=ncca_citation,
            )
            concepts.append(concept)
    return concepts


# Per-subject per-topic asset request count (for the comparison pipeline)
ASSET_REQUEST_BY_SUBJECT: dict[str, int] = {
    "mathematics": 30,
    "english": 24,
    "gaeilge": 26,
    "chemistry": 22,
    "geography": 20,
    "physics": 24,
    "biology": 26,
    "computer_science": 18,
}


__all__ = [
    "ASSET_REQUEST_BY_SUBJECT",
    "NCCA_KEY_COMPETENCIES",
    "SUBJECT_SPECIALITIES",
    "CurriculumConcept",
    "build_curriculum_concepts",
]
