"""Unofficial certificate rendering.

Every certificate carries an explicit "UNOFFICIAL" banner — never a
credential, always a celebration of progress. The shapes mirror the
NCCA Junior Cycle / Leaving Cycle / CBA / Short Course surfaces plus
the equivalences for the other 7 subnations.

Why markdown? The frontend already supports marimo's markdown rendering
and the same text exports cleanly to PDF via marimo export to PDF.
The metadata dict carries the structured fields so the UI can render
badges, ribbons, and progress bars.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Literal, Optional


AwardType = Literal[
    "junior_cycle",
    "leaving_cycle",
    "cba",
    "short_course",
    "gcse",
    "a_level",
    "national_5",
    "higher",
    "advanced_higher",
    "l1lp",
    "l2lp",
    "special_education",
]


@dataclass(frozen=True)
class CertificateRecord:
    """A single certificate record."""

    learner_id: str
    learner_name: str
    award_type: AwardType
    award_title: str
    jurisdiction: str
    subject_slug: Optional[str] = None
    outcomes_covered: tuple[str, ...] = field(default_factory=tuple)
    descriptor: Literal[
        "Exceptional",
        "Above expectations",
        "In line with expectations",
        "Yet to meet expectations",
    ] = "In line with expectations"
    issued_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


def render_certificate_markdown(cert: CertificateRecord) -> tuple[str, dict[str, str]]:
    """Render the certificate as markdown + a metadata dict.

    The metadata dict is keyed by `AwardType.<LOWER>` strings — same shape
    as the Phase-3 ``AwardType`` enum used in the Convex schema.
    """
    outcomes_section = ""
    if cert.outcomes_covered:
        bullet_list = "\n".join(f"- `{oid}`" for oid in cert.outcomes_covered)
        outcomes_section = f"\n### Learning outcomes covered\n\n{bullet_list}\n"

    md = f"""# UNOFFICIAL Certificate of Achievement

> **This is an unofficial, in-product record of progress.** It is not a
> credential issued by any awarding body and is **not validated against
> any external assessment record.**

## Award details

- **Learner:** {cert.learner_name}
- **Award:** {cert.award_title}
- **Award type:** `{cert.award_type}`
- **Jurisdiction:** {cert.jurisdiction}
- **Subject:** {cert.subject_slug or "(general)"}
- **Descriptor:** {cert.descriptor}
- **Issued at:** {cert.issued_at.isoformat()}
{outcomes_section}

---

*Generated by gemini_hackathon (unofficial, in-product, celebratory only).
Uses the NCCA CBA descriptor vocabulary for "descriptor" and the
canonical AwardType enum from Phase 3 of the per-subnation-user-context
openspec change.*
"""
    metadata = {
        "learner_id": cert.learner_id,
        "learner_name": cert.learner_name,
        "award_type": cert.award_type,
        "award_title": cert.award_title,
        "jurisdiction": cert.jurisdiction,
        "subject_slug": cert.subject_slug or "",
        "descriptor": cert.descriptor,
        "issued_at": cert.issued_at.isoformat(),
        "outcomes_covered": ",".join(cert.outcomes_covered),
    }
    return md, metadata


__all__ = [
    "AwardType",
    "CertificateRecord",
    "render_certificate_markdown",
]
