/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as ArchipelagoRouteImport } from './routes/archipelago'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as EquivalencyRouteImport } from './routes/equivalency'
import { Route as FindResourcesRouteImport } from './routes/find-resources'
import { Route as SafeguardingRouteImport } from './routes/safeguarding'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as ApiCopilotkitRouteImport } from './routes/api/copilotkit'
import { Route as ApiDuckdbRouteImport } from './routes/api/duckdb'
import { Route as ApiThemesRouteImport } from './routes/api/themes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchipelagoRoute = ArchipelagoRouteImport.update({
  id: '/archipelago',
  path: '/archipelago',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const EquivalencyRoute = EquivalencyRouteImport.update({
  id: '/equivalency',
  path: '/equivalency',
  getParentRoute: () => rootRouteImport,
} as any)
const FindResourcesRoute = FindResourcesRouteImport.update({
  id: '/find-resources',
  path: '/find-resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SafeguardingRoute = SafeguardingRouteImport.update({
  id: '/safeguarding',
  path: '/safeguarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCopilotkitRoute = ApiCopilotkitRouteImport.update({
  id: '/api/copilotkit',
  path: '/api/copilotkit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDuckdbRoute = ApiDuckdbRouteImport.update({
  id: '/api/duckdb',
  path: '/api/duckdb',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiThemesRoute = ApiThemesRouteImport.update({
  id: '/api/themes',
  path: '/api/themes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/archipelago': typeof ArchipelagoRoute
  '/compare': typeof CompareRoute
  '/equivalency': typeof EquivalencyRoute
  '/find-resources': typeof FindResourcesRoute
  '/safeguarding': typeof SafeguardingRoute
  '/subjects': typeof SubjectsRoute
  '/api/copilotkit': typeof ApiCopilotkitRoute
  '/api/duckdb': typeof ApiDuckdbRoute
  '/api/themes': typeof ApiThemesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/archipelago': typeof ArchipelagoRoute
  '/compare': typeof CompareRoute
  '/equivalency': typeof EquivalencyRoute
  '/find-resources': typeof FindResourcesRoute
  '/safeguarding': typeof SafeguardingRoute
  '/subjects': typeof SubjectsRoute
  '/api/copilotkit': typeof ApiCopilotkitRoute
  '/api/duckdb': typeof ApiDuckdbRoute
  '/api/themes': typeof ApiThemesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/archipelago': typeof ArchipelagoRoute
  '/compare': typeof CompareRoute
  '/equivalency': typeof EquivalencyRoute
  '/find-resources': typeof FindResourcesRoute
  '/safeguarding': typeof SafeguardingRoute
  '/subjects': typeof SubjectsRoute
  '/api/copilotkit': typeof ApiCopilotkitRoute
  '/api/duckdb': typeof ApiDuckdbRoute
  '/api/themes': typeof ApiThemesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/archipelago'
    | '/compare'
    | '/equivalency'
    | '/find-resources'
    | '/safeguarding'
    | '/subjects'
    | '/api/copilotkit'
    | '/api/duckdb'
    | '/api/themes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/archipelago'
    | '/compare'
    | '/equivalency'
    | '/find-resources'
    | '/safeguarding'
    | '/subjects'
    | '/api/copilotkit'
    | '/api/duckdb'
    | '/api/themes'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/archipelago'
    | '/compare'
    | '/equivalency'
    | '/find-resources'
    | '/safeguarding'
    | '/subjects'
    | '/api/copilotkit'
    | '/api/duckdb'
    | '/api/themes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  ArchipelagoRoute: typeof ArchipelagoRoute
  CompareRoute: typeof CompareRoute
  EquivalencyRoute: typeof EquivalencyRoute
  FindResourcesRoute: typeof FindResourcesRoute
  SafeguardingRoute: typeof SafeguardingRoute
  SubjectsRoute: typeof SubjectsRoute
  ApiCopilotkitRoute: typeof ApiCopilotkitRoute
  ApiDuckdbRoute: typeof ApiDuckdbRoute
  ApiThemesRoute: typeof ApiThemesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archipelago': {
      id: '/archipelago'
      path: '/archipelago'
      fullPath: '/archipelago'
      preLoaderRoute: typeof ArchipelagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equivalency': {
      id: '/equivalency'
      path: '/equivalency'
      fullPath: '/equivalency'
      preLoaderRoute: typeof EquivalencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-resources': {
      id: '/find-resources'
      path: '/find-resources'
      fullPath: '/find-resources'
      preLoaderRoute: typeof FindResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safeguarding': {
      id: '/safeguarding'
      path: '/safeguarding'
      fullPath: '/safeguarding'
      preLoaderRoute: typeof SafeguardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/copilotkit': {
      id: '/api/copilotkit'
      path: '/api/copilotkit'
      fullPath: '/api/copilotkit'
      preLoaderRoute: typeof ApiCopilotkitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/duckdb': {
      id: '/api/duckdb'
      path: '/api/duckdb'
      fullPath: '/api/duckdb'
      preLoaderRoute: typeof ApiDuckdbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/themes': {
      id: '/api/themes'
      path: '/api/themes'
      fullPath: '/api/themes'
      preLoaderRoute: typeof ApiThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  ArchipelagoRoute: ArchipelagoRoute,
  CompareRoute: CompareRoute,
  EquivalencyRoute: EquivalencyRoute,
  FindResourcesRoute: FindResourcesRoute,
  SafeguardingRoute: SafeguardingRoute,
  SubjectsRoute: SubjectsRoute,
  ApiCopilotkitRoute: ApiCopilotkitRoute,
  ApiDuckdbRoute: ApiDuckdbRoute,
  ApiThemesRoute: ApiThemesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
