"""gemini_hackathon_gradio._common.cloud_run_deploy — the multi-studio Cloud Run generator.

Phase 8 of the GCP-first refactor. `editorial_studio/deploy.py` already
had a working single-studio Cloud Run generator (Dockerfile.cloudrun +
cloudbuild.cloudrun.yaml + `deploy_command()`) — this module generalises
that proven template to the other 4 Gradio studios
(`an_scrudu`, `anam_education`, `oideachais_mission_control`,
`oideachais_pdf_review`), which were previously HF-Spaces-only.

`editorial_studio` is intentionally NOT included in `STUDIO_TARGETS` —
it stays on its own bespoke FastAPI+Gradio deploy path
(`editorial_studio/deploy.py`, `uvicorn ...:app`) since it's a full ADK 2
agent-backed service with an `/api/health` route, not a plain
`gr.Blocks().launch()` app like the other 4.

Each of the other 4 is a plain Gradio Blocks app (`build_app() ->
gr.Blocks`, no FastAPI wrapper), so its Cloud Run container just calls
`.launch(server_name="0.0.0.0", server_port=8080)` directly — Gradio's
own dev server, not uvicorn.

`--min-instances=0` (scale-to-zero) for all 4, unlike editorial_studio's
`--min-instances=1` — these are secondary demo surfaces, not the
showcase; paying for an always-warm instance isn't justified for them.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class StudioTarget:
    """One Gradio studio's Cloud Run deployment target."""

    slug: str  # the directory name under gemini_hackathon_gradio/
    service_name: str  # the Cloud Run service name
    module: str  # the Python module exposing build_app()
    display_name: str


#: The 4 plain-Gradio-Blocks studios (editorial_studio excluded — see
#: the module docstring).
STUDIO_TARGETS: tuple[StudioTarget, ...] = (
    StudioTarget(
        slug="an_scrudu",
        service_name="gemini-hackathon-an-scrudu",
        module="gemini_hackathon_gradio.an_scrudu.app",
        display_name="An Scrúdú — LC Past-Paper Heatmap",
    ),
    StudioTarget(
        slug="anam_education",
        service_name="gemini-hackathon-anam-education",
        module="gemini_hackathon_gradio.anam_education.app",
        display_name="Anam Oideachais — 7-Feature Integration Studio",
    ),
    StudioTarget(
        slug="oideachais_mission_control",
        service_name="gemini-hackathon-mission-control",
        module="gemini_hackathon_gradio.oideachais_mission_control.app",
        display_name="Oideachais Mission Control — 5-Stage Control",
    ),
    StudioTarget(
        slug="oideachais_pdf_review",
        service_name="gemini-hackathon-pdf-review",
        module="gemini_hackathon_gradio.oideachais_pdf_review.app",
        display_name="Oideachais PDF Review — Human Review",
    ),
)


def dockerfile_for(target: StudioTarget) -> str:
    """Return the `Dockerfile.cloudrun` content for one studio.

    Mirrors `editorial_studio/deploy.py`'s `DOCKERFILE_CLOUDRUN` template
    (same 2-stage build), with a Gradio `.launch()` CMD instead of
    uvicorn (see the module docstring for why).
    """
    return f"""\
# syntax=docker/dockerfile:1.7
# Auto-generated by gemini_hackathon_gradio._common.cloud_run_deploy —
# do not hand-edit; re-run `python -m scripts.generate_cloud_run_studios`.

# ===== Stage 1: builder =====
FROM python:3.12-slim AS builder

WORKDIR /app

RUN pip install --no-cache-dir uv==0.5.0

COPY pyproject.toml uv.lock README.md ./
COPY gemini_hackathon ./gemini_hackathon
COPY gemini_hackathon_gradio ./gemini_hackathon_gradio
COPY gemini_hackathon_assets_fibo ./gemini_hackathon_assets_fibo
COPY baml_extracts ./baml_extracts
COPY baml_extracts_education ./baml_extracts_education
COPY cocoindex_flows ./cocoindex_flows
COPY dlt_pipelines ./dlt_pipelines
COPY themes ./themes
COPY data/ireland ./data/ireland

RUN uv sync --all-extras
RUN uv run baml-cli generate

# ===== Stage 2: runtime =====
FROM python:3.12-slim AS runtime

WORKDIR /app

RUN pip install --no-cache-dir uv==0.5.0
COPY --from=builder /app/.venv /app/.venv
COPY --from=builder /app/gemini_hackathon /app/gemini_hackathon
COPY --from=builder /app/gemini_hackathon_gradio /app/gemini_hackathon_gradio
COPY --from=builder /app/gemini_hackathon_assets_fibo /app/gemini_hackathon_assets_fibo
COPY --from=builder /app/baml_client /app/baml_client
COPY --from=builder /app/data/ireland /app/data/ireland
COPY --from=builder /app/themes /app/themes

ENV PATH="/app/.venv/bin:$PATH"
ENV GRADIO_SERVER_NAME=0.0.0.0
ENV GRADIO_SERVER_PORT=8080

HEALTHCHECK --interval=30s --timeout=5s --start-period=15s --retries=3 \\
    CMD curl -f http://localhost:8080/ || exit 1

EXPOSE 8080

# {target.display_name}
CMD ["uv", "run", "python", "-c", \\
     "from {target.module} import build_app; build_app().launch(server_name='0.0.0.0', server_port=8080)"]
"""


def cloudbuild_yaml_for(target: StudioTarget) -> str:
    """Return the `cloudbuild.cloudrun.yaml` content for one studio.

    Mirrors `editorial_studio/deploy.py`'s `CLOUDBUILD_CLOUDRUN` template,
    with `--min-instances=0` (scale-to-zero — see module docstring).
    """
    return f"""\
# Cloud Build pipeline for {target.display_name}.
# Auto-generated by gemini_hackathon_gradio._common.cloud_run_deploy.
#
# Submit:
#   gcloud builds submit --config=gemini_hackathon_gradio/{target.slug}/cloudbuild.cloudrun.yaml \\
#     --substitutions=_REGION=europe-west1,_IMAGE_URL=IMAGE_URL

steps:
  - name: "gcr.io/cloud-builders/docker:latest"
    id: "build"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -euo pipefail
        docker build \\
          --build-arg BUILDKIT_INLINE_CACHE=1 \\
          -t "$_IMAGE_URL" \\
          -f gemini_hackathon_gradio/{target.slug}/Dockerfile.cloudrun \\
          .

  - name: "gcr.io/cloud-builders/docker:latest"
    id: "push"
    entrypoint: "bash"
    args: ["-c", "docker push $_IMAGE_URL"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:latest"
    id: "deploy-cloud-run"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "{target.service_name}"
      - "--project=$PROJECT_ID"
      - "--region=$_REGION"
      - "--platform=managed"
      - "--image=$_IMAGE_URL"
      - "--memory=2Gi"
      - "--cpu=2"
      - "--timeout=300"
      - "--concurrency=40"
      - "--min-instances=0"
      - "--max-instances=5"
      - "--allow-unauthenticated"
      - "--port=8080"
      - "--set-env-vars=MODEL_PROFILE=hackathon,GEMINI_BACKEND=vertex,GOOGLE_CLOUD_LOCATION=$_REGION"
      - "--set-secrets=GEMINI_API_KEY=projects/$PROJECT_ID/secrets/GEMINI_API_KEY:latest"

substitutions:
  _REGION: europe-west1
  _IMAGE_URL: ""

timeout: 1800s
options:
  logging: CLOUD_LOGGING_ONLY
"""


def deploy_command_for(target: StudioTarget, *, project_id: str, region: str = "europe-west1") -> list[str]:
    """The `gcloud run deploy` command (for local + CI use)."""
    return [
        "gcloud", "run", "deploy", target.service_name,
        f"--project={project_id}",
        f"--region={region}",
        "--platform=managed",
        f"--image=gcr.io/{project_id}/{target.service_name}:latest",
        "--memory=2Gi",
        "--cpu=2",
        "--min-instances=0",
        "--max-instances=5",
        "--allow-unauthenticated",
        "--port=8080",
    ]


__all__ = [
    "STUDIO_TARGETS",
    "StudioTarget",
    "cloudbuild_yaml_for",
    "deploy_command_for",
    "dockerfile_for",
]
